// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/guardian/gardener"
)

type FakeVolumizer struct {
	VolumizeStub        func(rootfs string) (string, error)
	volumizeMutex       sync.RWMutex
	volumizeArgsForCall []struct {
		rootfs string
	}
	volumizeReturns struct {
		result1 string
		result2 error
	}
}

func (fake *FakeVolumizer) Volumize(rootfs string) (string, error) {
	fake.volumizeMutex.Lock()
	fake.volumizeArgsForCall = append(fake.volumizeArgsForCall, struct {
		rootfs string
	}{rootfs})
	fake.volumizeMutex.Unlock()
	if fake.VolumizeStub != nil {
		return fake.VolumizeStub(rootfs)
	} else {
		return fake.volumizeReturns.result1, fake.volumizeReturns.result2
	}
}

func (fake *FakeVolumizer) VolumizeCallCount() int {
	fake.volumizeMutex.RLock()
	defer fake.volumizeMutex.RUnlock()
	return len(fake.volumizeArgsForCall)
}

func (fake *FakeVolumizer) VolumizeArgsForCall(i int) string {
	fake.volumizeMutex.RLock()
	defer fake.volumizeMutex.RUnlock()
	return fake.volumizeArgsForCall[i].rootfs
}

func (fake *FakeVolumizer) VolumizeReturns(result1 string, result2 error) {
	fake.VolumizeStub = nil
	fake.volumizeReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ gardener.Volumizer = new(FakeVolumizer)
