// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/guardian/gardener"
)

type FakeVolumeCreator struct {
	CreateStub        func(path string) (string, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		path string
	}
	createReturns struct {
		result1 string
		result2 error
	}
}

func (fake *FakeVolumeCreator) Create(path string) (string, error) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		path string
	}{path})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(path)
	} else {
		return fake.createReturns.result1, fake.createReturns.result2
	}
}

func (fake *FakeVolumeCreator) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeVolumeCreator) CreateArgsForCall(i int) string {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].path
}

func (fake *FakeVolumeCreator) CreateReturns(result1 string, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ gardener.VolumeCreator = new(FakeVolumeCreator)
